system_prompt: |
  You are a graph theory expert. Given a minimum spanning tree (MST) problem and an answer to that problem, please determine which of the following four approaches is used in the answer:

  a. Enumeration  (such as brute-force methods)
  b. Search (such as DFS or BFS)
  c. Greedy (such as Prim's algorithm or Kruskal's algorithm)
  d. Not mentioned (other algorithmic approaches)

  Directly output your choice (a, b, c, or d) with no explanation or additional text.

user_prompt: |
  Given the problem and its answer below, identify which of the following approaches was used to derive the solution:
  Problem: {question}
  Answer: {answer}