from .MKC import MKC_Task
from .MCP import MCP_Task
from .DistanceK import DistanceK_Task
from .DistanceThreshold import DistanceThreshold_Task
from .LCA import LCA_Task
from .Triangle import Triangle_Task
from .MF import MaximumFlow_Task
from .MST import MST_Task
from .PathSum import PathSum_Task
from .DegreeK import DegreeK_Task
from .MaxDegree import MaxDegree_Task
from .Diameter import Diameter_Task